
; Include file- GAME2.INC
; Globals for GAME2.ASM

global C update_screen:far
global C _shoot_lazer:near
global C _shoot_lazer_c:far
global C _transport:far
global C _push:far
global C _shoot_c:far
global C _shoot:near
global C _shoot_fire:near
global C _shoot_fire_c:far
global C _shoot_seeker:near
global C _shoot_seeker_c:far
global C _shoot_missile:near
global C _shoot_missile_c:far
global C _move:far
global C _push:far
global C parsedir:far