#
# "We have Autoconf at home"
# Autoconf at home:
#

all: cc cxx msse2 mavx mneon

include arch/compat.inc
include platform.inc
include arch/${PLATFORM}/Makefile.in

.PHONY: all cc cxx msse2 mavx mneon

BOILERPLATE := test.c -c -o/dev/null >/dev/null 2>&1

cc:
	@echo "Checking for working cc..."
	@${CC} ${BOILERPLATE}

cxx:
	@echo "Checking for working cxx..."
	@${CXX} ${BOILERPLATE}

# Check for SSE2 on x86. This is implicit for x86-64 but doesn't hurt.
msse2: cc
	@echo "Checking for -msse2..."
	@if ${CC} -msse2 ${BOILERPLATE}; then \
		echo "MSSE2:=-msse2" >>platform.inc; \
	fi

# Check for AVX, currently including AVX2 (until it's removed from the renderer).
mavx: cc
	@echo "Checking for -mavx..."
	@if ${CC} -mavx -mavx2 ${BOILERPLATE}; then \
		echo "MAVX:=-mavx -mavx2" >>platform.inc; \
	elif ${CC} -mavx ${BOILERPLATE}; then \
		echo "MAVX:=-mavx" >>platform.inc; \
	fi

# Should work for 32-bit but fail for AArch64, which has Neon anyway.
mneon: cc
	@echo "Checking for -march=armv7+simd..."
	@if ${CC} -march=armv7-a+simd ${BOILERPLATE}; then \
		echo "MNEON:=-march=armv7-a+simd" >>platform.inc; \
	fi
