#
# "We have Autoconf at home"
# Autoconf at home:
#

all: cc cxx msse2 mavx mneon

.PHONY: all cc cxx msse2 mavx mneon

include platform.inc
include arch/${PLATFORM}/Makefile.in
include arch/defaults.inc
include arch/compat.inc

CC_FULL := ${CC} ${ARCH_CFLAGS}
CXX_FULL := ${CXX} ${ARCH_CFLAGS}

BOILERPLATE := arch/test.c -c -o/dev/null >/dev/null 2>&1

cc:
	@echo "Checking for working cc..."
	@${CC_FULL} ${BOILERPLATE}

cxx:
	@echo "Checking for working cxx..."
	@${CXX_FULL} ${BOILERPLATE}

# Check for SSE2 on x86. This is implicit for x86-64 but doesn't hurt.
msse2: cc
	@echo "Checking for -msse2..."
	@if ${CC_FULL} -msse2 ${BOILERPLATE}; then \
		echo "MSSE2:=-msse2" >>platform.inc; \
	fi

# Check for AVX, currently including AVX2 (until it's removed from the renderer).
mavx: cc
	@echo "Checking for -mavx..."
	@if ${CC_FULL} -mavx -mavx2 ${BOILERPLATE}; then \
		echo "MAVX:=-mavx -mavx2" >>platform.inc; \
	elif ${CC_FULL} -mavx ${BOILERPLATE}; then \
		echo "MAVX:=-mavx" >>platform.inc; \
	fi

# Should work for 32-bit but fail for AArch64, which has Neon anyway.
mneon: cc
ifneq (${NEON_FLOAT_ABI},)
	@echo "Checking for -mfpu=neon..."
	@${CC_FULL} -mfpu=neon -mfloat-abi='${NEON_FLOAT_ABI}' ${BOILERPLATE}
	@echo "MNEON := -mfpu=neon -mfloat-abi=${NEON_FLOAT_ABI}" >>platform.inc
else
	@true
endif
