#
# "We have Autoconf at home"
# Autoconf at home:
#

all:

.PHONY: all

include platform.inc

# Skip meta target platforms.
ifeq ($(filter darwin-dist android,${SUBPLATFORM}),)

SUPPRESS_META_TARGETS := 1

include arch/${PLATFORM}/Makefile.in
include arch/defaults.inc
include arch/compat.inc

CC_FULL := ${CC} ${ARCH_CFLAGS}
CXX_FULL := ${CXX} ${ARCH_CFLAGS}

TEST := arch/test.c
BOILERPLATE := -c -o/dev/null >/dev/null 2>&1

all: cc cxx msse2 mavx mneon mrvv
.PHONY: cc cxx msse2 mavx mneon mrvv

cc:
	@echo "Checking for working cc..."
	@${CC_FULL} ${TEST} ${BOILERPLATE}

cxx:
	@echo "Checking for working cxx..."
	@${CXX_FULL} ${TEST} ${BOILERPLATE}

# Check for SSE2 on x86. This is implicit for x86-64 but doesn't hurt.
msse2: cc
	@echo "Checking for -msse2..."
	@if ${CC_FULL} -msse2 ${TEST} ${BOILERPLATE}; then \
		echo "MSSE2:=-msse2" >>platform.inc; \
	fi

# Check for AVX, currently including AVX2 (until it's removed from the renderer).
mavx: cc
	@echo "Checking for -mavx..."
	@if ${CC_FULL} -mavx -mavx2 ${TEST} ${BOILERPLATE}; then \
		echo "MAVX:=-mavx -mavx2" >>platform.inc; \
	elif ${CC_FULL} -mavx ${TEST} ${BOILERPLATE}; then \
		echo "MAVX:=-mavx" >>platform.inc; \
	fi

# Should work for 32-bit but fail for AArch64, which has Neon anyway.
mneon: cc
ifneq (${NEON_FLOAT_ABI},)
	@echo "Checking for -mfpu=neon..."
	@${CC_FULL} -mfpu=neon -mfloat-abi='${NEON_FLOAT_ABI}' ${TEST} ${BOILERPLATE}
	@echo "MNEON := -mfpu=neon -mfloat-abi=${NEON_FLOAT_ABI}" >>platform.inc
else
	@true
endif

mrvv: cc
ifneq (${RVV_ABI},)
	@echo "Checking for -march=${RVV_ABI}..."
	@${CC} -march=${RVV_ABI} ${TEST} ${BOILERPLATE};
	@echo "MRVV := -march=${RVV_ABI}" >>platform.inc;
else
	@true
endif

else # meta target

all:
	@true

endif
