#
# MegaZeux version information for building and packaging
#
# Pre-releases should be titled [old version]-GIT.
# Pre-releases with world format changes should be
# be [new version]-PRE and also enable the pre-release nag.
#
# NOTE: VERSION must be kept in quotes, in case spaces are used.
# NOTE: TARGET must NOT be kept in quotes, and spaces CANNOT be used.
#

VERSION="2.93-GIT"
TARGET=mzxgit

PRERELEASE=0
