#include "version.h"
#define PLATFORM "xcode"
#define CONFDIR "../Resources"
#define CONFFILE "config.txt"
#define USERCONFFILE ".megazeux-config"
#define SHAREDIR "../Resources"
#define CONFIG_SDL
#define CONFIG_EDITOR
#define CONFIG_HELPSYS
#define CONFIG_RENDER_SOFT
#define CONFIG_RENDER_SOFTSCALE
#define CONFIG_RENDER_GL_FIXED
#define CONFIG_RENDER_GL_PROGRAM
#define CONFIG_ENABLE_SCREENSHOTS
#define CONFIG_XMP
#define CONFIG_AUDIO
#define CONFIG_AUDIO_MOD_SYSTEM
#define CONFIG_REALITY
#define CONFIG_VORBIS
#define CONFIG_PNG
#define CONFIG_ICON
#define CONFIG_MODULAR
#define CONFIG_CHECK_ALLOC
#define CONFIG_COUNTER_HASH_TABLES
#define CONFIG_GAMECONTROLLERDB
