#
# win32 makefile generics
#

all: subdir
debug: subdir-debug

# windows requires a binary extension
BINEXT    = .exe

# location of strip (must be defined)
STRIP     = strip --strip-unneeded

# standard libraries
LIBS     += ../${GDM2S3M}/libgdm2s3m.a ../${MODPLUG}/libmodplug.a \
            -lvorbisfile -lvorbis -logg -lopengl32

# debug does something different
ifdef DEBUG
LIBS     += -mconsole
else
LIBS     += -mwindows
endif
