#
# linux-static makefile generics
#

all: subdir
debug: subdir-debug

# location of strip (must be defined)
STRIP     = strip --strip-unneeded

# standard libraries
LIBS      = ../${GDM2S3M}/libgdm2s3m.a ../${MODPLUG}/libmodplug.a \
            ${PREFIX}/lib/libvorbisfile.a ${PREFIX}/lib/libvorbis.a \
            ${PREFIX}/lib/libogg.a ${PREFIX}/lib/libstdc++.a \
            -L${PREFIX}/lib -lSDL -lpthread

