#
# linux-static makefile generics
#

# location of strip (must be defined)
STRIP = strip --strip-unneeded

# standard libraries
LIBS += `sdl-config --static-libs` ${PREFIX}/lib/libvorbisfile.a \
        ${PREFIX}/lib/libvorbis.a ${PREFIX}/lib/libogg.a

# switch locking method
mzx_includes += -DPTHREAD_MUTEXES

# enable stack protector for debug builds
ifdef DEBUG
CFLAGS   += -fstack-protector-all
CXXFLAGS += -fstack-protector-all
endif
