#
# macos makefile generics
#

all: subdir
debug: subdir-debug

# location of strip (must be defined)
STRIP ?= strip

# standard libraries
LIBS  += ../${GDM2S3M}/libgdm2s3m.a ../${MODPLUG}/libmodplug.a \
         -L${PREFIX}/lib -lvorbis -logg -framework Cocoa
