#
# macos makefile generics
#

# location of strip (must be defined)
STRIP     = true

# standard linker includes
INCLUDES  = -I${PREFIX}/include -I${PREFIX}/include/SDL

# standard libraries
LIBS      = -L$(PREFIX)/lib -lSDL -lpthread
