#
# OpenBSD makefile generics
#

# location of strip (must be defined)
STRIP = strip --strip-unneeded

# standard libraries
SDL_LDFLAGS    = `sdl-config --static-libs`
VORBIS_LDFLAGS = ${PREFIX}/lib/libvorbisfile.a \
                 ${PREFIX}/lib/libvorbis.a ${PREFIX}/lib/libogg.a

# need PNG to be statically linked (inc. zlib)
LIBPNG_CFLAGS = `libpng-config --cflags`
LIBPNG_LDFLAGS = `libpng-config --static --libs`
