#!/bin/sh
NAME=tremor
# Latest GIT of libtremor lowmem branch.
VERSION=e5a6b2e7048d054c48aca5b4b8603733365383a7
EXTENSION=tar.gz
FILENAME=$NAME-$VERSION.$EXTENSION

VERPATH=`printf $VERSION | cut -c1-7`

pkg-download $FILENAME nohash "https://git.xiph.org/?p=tremor.git;a=snapshot;h=$VERSION;sf=tgz"
cd $NAME-$VERPATH
sed -i 's/AM_CONFIG_HEADER/AC_CONFIG_HEADERS/' configure.in
./autogen.sh --prefix="$PREFIX" --host=arm-none-eabi --disable-shared --enable-static --disable-oggtest
make
make -j1 install
