.TH MEGAZEUX 1 "2007-05-05"
.SH NAME
MegaZeux - Simple Game Creation System (GCS)

.SH SYNOPSIS
.B megazeux
.SH DESCRIPTION
MegaZeux is a Game Creation System (GCS), inspired by Epic MegaGames' ZZT,
first released by Gregory Janson in 1994.  It was recently ported from 16bit
MSDOS C/ASM to portable SDL C/C++, improving its platform support and
hardware compatibility.

.SH FILES
.TP
.B /etc/megazeux-config
This file contains setting for \fBmegazeux\fP. All of the variables can
also be passed as options to the program which will override the settings
in this file, e.g. \fBmegazeux fullscreen=1\fP

.SH AUTHORS
.B MegaZeux
was written by Gregory Janson, Charles Goetzman,
Gilead Kutnick <exophase@gmail.com>,
Alistair John Strachan <alistair@devzero.co.uk> and
various other contributors during 1996-2007.
