.TH MEGAZEUX 1 "2017-11-22"
.SH NAME
MegaZeux - Simple Game Creation System (GCS)

.SH SYNOPSIS
.B megazeux
.SH DESCRIPTION
MegaZeux is a Game Creation System (GCS), inspired by Epic MegaGames' ZZT,
first released by Alexis Janson in 1994.  Originally written for DOS,
MegaZeux is now available on a wide variety of platforms.

.SH FILES
.TP
.B /etc/megazeux-config
This file contains setting for \fBmegazeux\fP. All of the variables can
also be passed as options to the program which will override the settings
in this file, e.g. \fBmegazeux fullscreen=1\fP

.SH AUTHORS
.B MegaZeux
was written by Alexis Janson, Charles Goetzman,
Gilead Kutnick <exophase@gmail.com>,
Alistair John Strachan <alistair@devzero.co.uk>,
Alice Rowan <petrifiedrowan@gmail.com>,
and various other contributors during 1996-2017.
