#define MZX_DEFAULT_CHR "/usr/share/megazeux/mzx_default.chr"
#define MZX_BLANK_CHR "/usr/share/megazeux/mzx_blank.chr"
#define MZX_SMZX_CHR "/usr/share/megazeux/mzx_smzx.chr"
#define MZX_ASCII_CHR "/usr/share/megazeux/mzx_ascii.chr"
#define SMZX_PAL "/usr/share/megazeux/smzx.pal"
#define MZX_HELP_FIL "/usr/share/megazeux/mzx_help.fil"
#define CONFIG_TXT "/etc/megazeux-config"
