name: Regression tests

env:
  MZXDEPS_DEBIAN_SDL2:  "zlib1g-dev libpng-dev libogg-dev libvorbis-dev libsdl2-dev"
  MZXDEPS_DEBIAN_MISC:  "libsdl1.2-dev libegl1-mesa-dev libmikmod-dev libopenmpt-dev"
  MZXDEPS_MACOS:        "libpng libogg libvorbis sdl2"
  MZX_MAKE:             "make -j4"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  #
  # Platform variants and distribution packages.
  #
  flatpak:
    runs-on: ubuntu-latest
    container: freedesktopsdk/flatpak
    steps:
      - uses: actions/checkout@v4
      - name: Build and install
        run: |
          cd scripts/pkg/flatpak;
          flatpak-builder --force-clean --sandbox --user --install --ccache --mirror-screenshots-url=https://dl.flathub.org/media/ --repo=repo builddir com.digitalmzx.MegaZeux.yml
      - name: Export bundle
        run: |
          cd scripts/pkg/flatpak;
          flatpak build-bundle repo mzxgit.flatpak com.digitalmzx.MegaZeux
